apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zoochacha-admin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Goorm-Cloud/Zoochacha_k8s.git
    targetRevision: HEAD
    path: admin_service   
  destination:
    server: https://kubernetes.default.svc
    namespace: zoochacha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
