apiVersion: v1
kind: Service
metadata:
  name: zoochacha-admin-service
  namespace: zoochacha-admin
spec:
  type: ClusterIP
  selector:
    app: zoochacha-admin-service
  ports:
    - protocol: TCP
      port: 5000        
      targetPort: 8001 