apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: zoochacha
data:
  nginx.conf: |
    worker_processes auto;
    events {
        worker_connections 1024;
    }
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # SSL 설정
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        upstream flask_admin_service {
            server admin-server.zoochacha.svc.cluster.local:8001;
        }

        upstream map_service {
            server map-server.zoochacha.svc.cluster.local:8002;
        }

        upstream reservation_service {
            server reservation-server.zoochacha.svc.cluster.local:8003;
        }

        upstream reservation_detail_service {
            server rds-server.zoochacha.svc.cluster.local:8004;
        }

        # HTTP -> HTTPS 리디렉트
        server {
            listen 80 proxy_protocol;
            server_name zoochacha.online www.zoochacha.online;
            return 301 https://$host$request_uri;
        }

        # HTTPS 서버
        server {
            listen 443 ssl proxy_protocol;
            server_name zoochacha.online www.zoochacha.online;

            # 프록시 프로토콜 설정
            set_real_ip_from 0.0.0.0/0;
            real_ip_header proxy_protocol;

            # 메인 페이지 (지도 서비스)
            location = / {
                return 301 /map/;
            }

            location / {
                proxy_pass http://map_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering off;
            }

            # 주차장 관련 API (예약 페이지)
            location /parking-lot {
                proxy_pass http://reservation_service;
                proxy_set_header Host $host;
            }

            location ~ ^/parking-lot/(\d+)$ {
                proxy_pass http://reservation_service;
            }

            location ~ ^/reservation/(\d+)/reserve$ {
                proxy_pass http://reservation_service;
            }

            # 예약 상세 페이지
            location ~ ^/reservation-detail/(\d+)$ {
                proxy_pass http://reservation_detail_service;
                proxy_set_header Host $host;
            }

            # 예약 상세 API 엔드포인트
            location ~ ^/reservation-detail/api/detail/(\d+)$ {
                proxy_pass http://reservation_detail_service;
            }

            # 예약 재활성화
            location ~ ^/reservation-detail/reactivate/(\d+)$ {
                proxy_pass http://reservation_detail_service;
            }

            # 예약 상세 페이지 - Not Found 리디렉트
            location /reservation-detail/not-found {
                proxy_pass http://reservation_detail_service;
            }

            # 관리자 페이지 (Admin Service)
            location /admin {
                proxy_pass http://flask_admin_service;
            }

            location /login {
                proxy_pass http://flask_admin_service;
            }

            location /role_check {
                proxy_pass http://flask_admin_service;
            }

            location /authorize {
                proxy_pass http://flask_admin_service;
            }

            location /logout {
                proxy_pass http://flask_admin_service;
            }

            location ~ ^/admin/reservation/(\d+)$ {
                proxy_pass http://flask_admin_service;
            }

            location ~ ^/admin/parkinglot/edit/(\d+)$ {
                proxy_pass http://flask_admin_service;
            }

            location /admin/parkinglot {
                proxy_pass http://flask_admin_service;
            }

            # 정적 파일 처리 (지도 서비스)
            location /static/ {
                proxy_pass http://map_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                expires -1;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires 0;
            }

            # 정적 파일 처리 (예약 서비스)
            location /reservation/static/ {
                proxy_pass http://reservation_service;
                proxy_redirect off;
                expires 7d;
                add_header Cache-Control "public, max-age=604800";
            }

            add_header Strict-Transport-Security "max-age=31536000" always;
            add_header X-Frame-Options DENY;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
        }
    }