# configMap 적용 후 해당 파일 적용 시킬것.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: zoochacha-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: zoochacha-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # 프록시 서버 엔드포인트를 AWS NLB로 생성
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80