apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-server
  namespace: zoochacha-map
spec:
  replicas: 1  # 서버는 확장 가능하도록 설정
  selector:
    matchLabels:
      app: map-server
  template:
    metadata:
      labels:
        app: map-server
    spec:
      containers:
        - name: map-server
          image: 651706756261.dkr.ecr.ap-northeast-2.amazonaws.com/map_service:3    # 민승님이 말아준 이미지 이후 수정 불가
          imagePullPolicy: Always

          # 민감정보 수정 후 감추는 작업 필수
          env:
            - name: DB_HOST
              value: "mysql.zoochacha-db.svc.cluster.local"   # db 서비스(ClusterIP) 앤드포인트
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "zoochacha"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: map-server
  namespace: zoochacha-map
spec:
  selector:
    app: map-server
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP